### PR TITLE
Fixed jQuery url

### PR DESCRIPTION
**Pull request by corpix**

### CODE REVIEW

**Comment by varya** [comment]
Thank you!

**Comment by arikon** [comment]
Explain me, please, why to specify protocol in url to jQuery?

**Comment by varya** [comment]
I can guess this was done to be able to develop (and see pages) on local computer.

**Comment by corpix** [comment]
toivonen, yeah, you are right.

**Comment by arikon** [comment]
The right way to do it was to drop your own bemhtml template for this elem to your project's `blocks-desktop` level.
Adding `http` protocol to the library is wrong because of sites using https to serve their pages.

**Comment by varya** [comment]
Whats wrong for https sites if they download jQuery from http?

**Comment by arikon** [comment]
Warnings in IE for example

**Comment by corpix** [comment]
Wow. Things I didn't know, thanks for explanation!

**Pull request merged**
