### PR TITLE
Extract slider items width processing

### PR DESCRIPTION
**Pull request by andre487**
In the b-slider block the _setItemsWidth method was extracted.

This work depends on the SERP-23458 task.

### CODE REVIEW

**Comment by tadatuta** [comment]
@Andre-487 the change looks good to me but are you sure about the branch?
we do not support `0.3` for a long time. current actual branch is `support/2.x` and all the changes should also land to `dev`

**Comment by andre487** [comment]
@tadatuta In the original repository the branch was "0.3.SERP" and it was the reason. In which branch can I propose this changes here?

**Comment by tadatuta** [comment]
the question was about in which branch **you** need it.
If you don't use this repo at all, I can port it to `dev` and `support/2.x` myself.

**Comment by andre487** [comment]
@tadatuta Ok, thanks!

**Comment by tadatuta** [comment]
landed in https://github.com/bem/bem-bl/commit/b9f41ea4db5d997266211c64d692e47047db49b0

**Comment by tadatuta** [comment]
thank you!

**Pull request closed without merging**
