### PR TITLE
b-page: delete js-params of i-ua block into b-page__head

### PR DESCRIPTION
**Pull request by alexbaumgertner**

### CODE REVIEW

**Comment by tadatuta** [comment]
if it was tested, lgtm

**Comment by alexbaumgertner** [comment]
How I can test it? Has `bem-bl` lib any BEMHTML tests?

**Comment by alexbaumgertner** [comment]
Oh, I made the PR to wrong branch, it should be `support/2.x` instead `dev`.

**Comment by tadatuta** [comment]
I think it's also needed in `dev` as well.

**Comment by tadatuta** [comment]
> Has bem-bl lib any BEMHTML tests?

https://github.com/bem/bem-bl/tree/dev/blocks-common/i-bem/__html

**Comment by alexbaumgertner** [comment]
Oh, I mean test for b-page block :)

**Pull request closed without merging**
