### PR TITLE
i-bem: use prototypes instead of singleton.

### PR DESCRIPTION
**Pull request by indutny**
In a few words, `i-bem` is always initializing `this._` routines and doing a lot of stuff on every render that could be done once at startup.

Obvious solution would be sharing routines object by encapsulating it in `BEMHTML`'s closure. I've did it by extending `bemhtml` grammar to allow writing raw javascript statements without `bem` sugar.

Also, I've removed `_start` check and initialization, because it was executing only once per render, but checked on every recursive call. Now all initialization is happening in the wrapper of xjst's `apply` function, which is located in `BEMContext.apply`.

@veged @narqo please review carefully. I'm absolutely sure in ometajs grammar changes, but you guys should help me in identifying any drawbacks that might be introduced by `i-bem.bemhtml` changes.

### CODE REVIEW

**Comment by indutny** [comment]
Perhaps, we should merge it ASAP. I've already solved one conflict with 0.3, and not really willing to keep it up-to-date for a long time.

**Comment by narqo** [comment]
I'll test it with our codebase in a day or two

**Comment by veged** [comment]
I looked at the code -- seems like all should work. We need only real proof on codebase by @narqo ;-)

**Comment by narqo** [comment]
It drops compability with this `BEM.I18N` hack from https://github.com/bem/bem-bl/blob/master/blocks-common/i-bem/__i18n/i-bem__i18n.bemhtml#L1

So this case isn't work now:

``` shell
› node -p -e "require('block.bemhtml.js').BEMHTML.apply({ block: 'i-bem', elem: 'i18n', keyset: 'kset', key: 'key' })"

[path]/block.bemhtml.js:1442
                this._buf.push(BEM.I18N(_$10keyset, _$10key, _$10params));
                               ^
ReferenceError: BEM is not defined
```

so as BEMHTML-template

``` js
block b-blah {
    content: BEM.I18N('kset', 'key')
}
```

I assume that it would returns `key`.

**Comment by narqo** [comment]
@indutny I looked carefully on our `BEM.I18N` hack, that I spoke about earlier. It was my fault to tell you that we are not using `this._start == false` guard in our code, crap, sorry :( 
But guess this is a good time to drop all those hacks off. Will rewrite them tomorrow. I don't think that anyone else use something like this.

**Comment by indutny** [comment]
Merged.

**Pull request closed without merging**
