### PR TITLE
Revert private field in package.json.

### PR DESCRIPTION
**Pull request by Yeti-or**
No need of bem-bl in npm registry

### CODE REVIEW

**Comment by tadatuta** [comment]
but it makes no harm to anybody, I think

**Comment by Yeti-or** [comment]
I thought so too, but @narqo told me that it was made on purpose, so nobody could push it to npm. Current status of bem-bl is: `npm ERR! 404 Unpublished by andrewblond on 2014-06-10`

**Comment by tadatuta** [comment]
@narqo please tell why it's so?

**Comment by narqo** [comment]
In #349 we decided that there is no practical reasons to have it in npm. But if you want to keep (and guarantee) actual version in npm registry — it's your burden, so I don't care.

**Comment by mishaberezin** [comment]
This PR makes no sense anymore.

**Pull request closed without merging**
