### PR TITLE
Fixes b-slider to slide on pointerleave event

### PR DESCRIPTION
**Pull request by dentuzhik**

### CODE REVIEW

**Comment by tadatuta** [comment]
Oleg @truerenton I've no idea if it's safe update. Can you, please, take a look?

**Comment by xoxulin** [comment]
All examples not work because there use `_some-example.pub.js`. There is no this files after build. We must use `_some-example.js` instead of `_some-example.pub.js`. Right?
/cc @dentuzhik @tadatuta @truerenton

**Comment by apostololeg** [comment]
@tadatuta @xoxulin @dentuzhik 
I'm sry for being late.
Currently, it is not clear the problem.
Without a specific reason does not make sense to accepting this PR.

**Comment by xoxulin** [comment]
However, I fixed the examples in  PR https://github.com/bem/bem-bl/pull/602

**Comment by xoxulin** [comment]
@tadatuta can I close this PR?

**Comment by mishaberezin** [comment]
I agree with @truerenton. If reasons of this PR is related to behaviour aspects only, it's better to leave current realization.

**Comment by xoxulin** [comment]
Close for https://github.com/bem/bem-bl/pull/603

**Pull request closed without merging**
