### PR TITLE
Prevent blocks to reinitialize during destructing

### PR DESCRIPTION
**Pull request by narqo**
Port of bem/bem-core#518

\cc @dfilatov @tadatuta

### CODE REVIEW

**Comment by narqo** [comment]
@tadatuta tests are failing with:

> $ nvm use 0.9
> N/A version is not installed yet
> The command "nvm use 0.9" failed and exited with 1 during setup.

Do we really need this amount of [Node.js versions in travis.yml](https://github.com/bem/bem-bl/blob/47a26153b7b4f6b47703392b5f5452adc1126dca/.travis.yml)?

**Comment by tadatuta** [comment]
@narqo nope, I removed it in https://github.com/bem/bem-bl/commit/5e10cfaea715c79750ab083a2492e086eae91f0d

**Comment by narqo** [comment]
:up:

**Comment by tadatuta** [comment]
@narqo is it enough to port fix to `support/2.x` or `support/1.x` as well?

**Comment by narqo** [comment]
@tadatuta it affects our current islands-\* codebase. So it would be nice to see it in 1.x

**Comment by tadatuta** [comment]
@narqo https://github.com/bem/bem-bl/releases/tag/v1.4.2

**Pull request merged**
