### PR TITLE
BEM-2121: b-slider: Slider at initializing overrides super method from i-bem__dom

### PR DESCRIPTION
**Pull request by xoxulin**
Issue https://github.com/bem/bem-bl/issues/599
- Separates private variable _elem from method _elem and renames in _menuElem

### CODE REVIEW

**Comment by Yeti-or** [comment]
:ok_hand:

**Comment by xoxulin** [comment]
@tadatuta I fixed issue https://github.com/bem/bem-bl/issues/599. What I must do now? Merge to dev or cherry pick to support / 1.x / 2.x ?

**Comment by tenorok** [comment]
:fire: burn!

**Comment by tadatuta** [comment]
@xoxulin both. Everything useful should land in `dev` and then be ported to support branch(es) you need.

**Comment by xoxulin** [comment]
@tadatuta good!

**Pull request merged**
